# Numpy Arrays

In [1]:
import numpy as np

In [2]:
var = [1,2,3,4,5,6]
var

[1, 2, 3, 4, 5, 6]

In [3]:
check = np.array(var)

In [4]:
type(check)

numpy.ndarray

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.random.rand(5,5)

array([[0.37775185, 0.35549997, 0.24581685, 0.10370764, 0.55350423],
       [0.55262522, 0.09301041, 0.13938355, 0.99325656, 0.81865662],
       [0.21901126, 0.38135148, 0.00922242, 0.71559715, 0.6635247 ],
       [0.92551872, 0.12292563, 0.94597977, 0.30074462, 0.86821706],
       [0.97788637, 0.24379128, 0.83590758, 0.46196654, 0.64421272]])

In [7]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones((2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
data = np.linspace(0,100,20)
data

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [11]:
len(data)

20

In [12]:
np.random.randn(10,5)

array([[ 0.42914888, -0.25245462,  1.04485403, -0.89102425,  0.24592877],
       [ 1.45570373, -0.6827371 , -0.39446362, -1.54966525, -1.500737  ],
       [ 2.28469629, -1.1101607 , -1.92550913, -0.33150978,  1.83060054],
       [-0.70226632,  0.45883639,  2.01924126, -0.08613057,  1.12917651],
       [ 2.26671878, -0.21989967,  1.25902021, -0.38241559, -0.59648193],
       [-2.04922084, -0.71189593, -0.72416078, -0.09103006, -0.18865126],
       [ 3.29082205,  1.05586803, -0.60263705, -0.57688945, -1.54013842],
       [ 0.79451684,  0.97052713, -0.14720402, -0.42121299, -0.5236357 ],
       [ 0.8569621 , -0.96292464,  1.09957129, -1.21284918,  0.47527623],
       [ 1.10277546, -1.43421934, -0.39207493,  1.66534256,  0.9384045 ]])

In [13]:
np.random.randint(0,10,(5,5)) 

array([[3, 9, 0, 8, 4],
       [4, 2, 0, 1, 6],
       [1, 2, 6, 2, 5],
       [5, 4, 4, 3, 6],
       [0, 5, 9, 8, 8]])

In [14]:
np.random.seed(100)
np.random.randn(5,5)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079],
       [ 0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081],
       [-0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869]])

In [15]:
np.random.seed(101)
np.random.randn(5,5)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795],
       [-0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206],
       [ 0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722],
       [ 0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072]])

In [16]:
np.random.seed(100)
np.random.randn(5,5)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079],
       [ 0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081],
       [-0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869]])

In [17]:
data.reshape(5,4) #data have 20 elements and 20 element should be in 2d array

array([[  0.        ,   5.26315789,  10.52631579,  15.78947368],
       [ 21.05263158,  26.31578947,  31.57894737,  36.84210526],
       [ 42.10526316,  47.36842105,  52.63157895,  57.89473684],
       [ 63.15789474,  68.42105263,  73.68421053,  78.94736842],
       [ 84.21052632,  89.47368421,  94.73684211, 100.        ]])

In [18]:
data1 = np.random.randint(0,100,20)

In [19]:
data1.max()

91

In [20]:
data1.min()

0

In [21]:
data1.argmax()

6

In [22]:
data1.argmin()

11

In [23]:
data1.argsort()

array([11, 17, 15,  0, 12,  2,  1,  5,  9,  3, 13,  4, 16, 14, 10, 19,  8,
       18,  7,  6], dtype=int64)

In [24]:
data1.shape

(20,)

In [25]:
data1.reshape(2,10)

array([[13, 30, 17, 53, 68, 50, 91, 91, 83, 53],
       [78,  0, 13, 57, 76,  3, 70,  3, 84, 79]])

# Indexing Selection

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr[2:4]

array([2, 3])

In [31]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
data_copy = arr.copy()

In [33]:
dat = arr

In [34]:
dat[:5] = 66

In [35]:
dat

array([66, 66, 66, 66, 66,  5,  6,  7,  8,  9, 10])

In [36]:
arr

array([66, 66, 66, 66, 66,  5,  6,  7,  8,  9, 10])

In [37]:
data_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
data_copy[5:] = 44

In [39]:
data_copy

array([ 0,  1,  2,  3,  4, 44, 44, 44, 44, 44, 44])

In [40]:
arr

array([66, 66, 66, 66, 66,  5,  6,  7,  8,  9, 10])

In [41]:
reshape_arr = arr[1:]
reshape_arr

array([66, 66, 66, 66,  5,  6,  7,  8,  9, 10])

In [42]:
reshape_arr = reshape_arr.reshape(5,2)

In [43]:
reshape_arr

array([[66, 66],
       [66, 66],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [44]:
reshape_arr[:,:1]

array([[66],
       [66],
       [ 5],
       [ 7],
       [ 9]])

In [45]:
arr == 66

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [46]:
bool_arr = arr<66

In [47]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [48]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

# Numpy Functions

In [49]:
arr = np.arange(1,26)

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [51]:
arr.sum()

325

In [52]:
arr.std()

7.211102550927978

In [53]:
arr.mean()

13.0

In [54]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [56]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625])

In [57]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [58]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
       0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ,
       0.04761905, 0.04545455, 0.04347826, 0.04166667, 0.04      ])

In [60]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175])

In [61]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582])

In [62]:
arr.var()

52.0

In [63]:
arr.std()

7.211102550927978

In [64]:
arr = arr.reshape(5,5)

In [65]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
arr.sum()

325

In [67]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [68]:
arr.sum(axis=1)

array([ 15,  40,  65,  90, 115])